source "https://rubygems.org"

# Specify your gem's dependencies in payments.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem 'grpc-tools', '~> 1.38.0.pre1'
gem 'ruby-protocol-buffers'
gem "grpc", "~> 1.31"