# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payment_service.proto", :syntax => :proto3) do
    add_message "payments.PaymentRequest" do
      optional :transaction_id, :string, 2
      optional :amount, :float, 1
    end
    add_message "payments.PaymentResponse" do
      optional :transaction_id, :string, 2
      optional :status, :enum, 1, "payments.PaymentResponse.Status"
    end
    add_enum "payments.PaymentResponse.Status" do
      value :UNKNOWN, 0
      value :PENDING, 1
      value :PROGRESS, 2
      value :DONE, 3
      value :FAILED, 4
    end
  end
end

module Payments
  PaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payments.PaymentRequest").msgclass
  PaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payments.PaymentResponse").msgclass
  PaymentResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payments.PaymentResponse.Status").enummodule
end
