# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payment_service.proto for package 'payments'

require 'grpc'
require_relative './payment_service_pb'

module Payments
  module Pay
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'payments.Pay'

      rpc :pay, ::Payments::PaymentRequest, ::Payments::PaymentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
