# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistence_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("persistence_service.proto", :syntax => :proto3) do
    add_message "persistence.PersistenceTransactionRequest" do
      optional :transaction_id, :string, 1
      optional :amount, :float, 2
      optional :status, :string, 3
    end
    add_message "persistence.PersistenceResponse" do
      optional :status, :enum, 1, "persistence.PersistenceResponse.Status"
    end
    add_enum "persistence.PersistenceResponse.Status" do
      value :OK, 0
      value :FAILED, 1
    end
  end
end

module Persistence
  PersistenceTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persistence.PersistenceTransactionRequest").msgclass
  PersistenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persistence.PersistenceResponse").msgclass
  PersistenceResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persistence.PersistenceResponse.Status").enummodule
end
